version: '3.4'

services:
  wappupeli:
    build: .
    container_name: wappupeli
    networks:
     - web
    volumes:
     - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=wappupeli"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:mun.wappubus.si"
      - "traefik.port=5000"
    restart: always
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app

networks:
  web:
    external: true
